### PR TITLE
Add package libtappp (C++ TAP producer library)

### PR DESCRIPTION
**Pull request by npatil-cpi**
Also added patches(internal),
1) Helper macros to generate YAML block.
2) Reset state so testapp can start new test-suit (i.e plan again)
    w/o terminating.

### CODE REVIEW

**Comment by npatil-cpi** [comment]
Stale. Closing.

**Comment by chardin-cpi** [comment]
Folks - my bad, we need this... So, I should have approved this a while ago.

**Comment by chardin-cpi** [comment]
@asimonetti-cpi and @npatil-cpi - the patches thru me off a little, so might see if there is a later version, else roll with this.

@asimonetti-cpi - we can talk later, but you will need to either external project the libtap in cmake for the core or update the Vagrant file to apt-get the dev package and the .github/workflows/ci.yaml

So, double check the patches - see if you still need them - but, get it in and move on.

We will likely end up with 2 tap producers in the giant scheme of things.

**Comment by chardin-cpi** [comment]
ok, well that makes more sense why I couldn't find @asimonetti-cpi patch in here.

**Pull request closed without merging**
