### PR TITLE
imx-gpu-viv: bump version to 6.4.0.p2.0

### PR DESCRIPTION
**Pull request by mfairman-cpi**
This version works with the 5.4 kernel.

Because this one package is used by i.mx8 and i.mx6, it may have implications on CPNK.  This bumps both of them but we could leave i.mx6 at the older version; I don't have a CPNK to test with, so if someone can try it out then we'll know if it work... or I can just leave the aarch32 version the way it was.

### CODE REVIEW

**Comment by mfairman-cpi** [comment]
Just to be clear, this may break the CPNK graphics and if so we'll either need to update CPNK to the 5.4 kernel or roll-back the imx-gpu-viv library to the previous version.  If we aren't worried about CPNK right now we can deal with it later...

**Comment by vgahlan-cpi** [comment]
> Just to be clear, this may break the CPNK graphics and if so we'll either need to update CPNK to the 5.4 kernel or roll-back the imx-gpu-viv library to the previous version. If we aren't worried about CPNK right now we can deal with it later...

Yes, I see that but ignored for the moment because CPNK need many changes to be work from emb-platform.  Ultimately if and when we migrate, we will do with common kernel.

**Comment by chardin-cpi** [comment]
At this point we might as well bump the kernel on the CPNK and make sure that compiles and just go from there. All of this leave the CPNK on a 4.x and move PBC and UCB to 5.4.x kernel just seems like an artificial headache. I'll try to "boot" a CPNK on the new kernel later today and post that PR - I don't have an display to test this stuff, but booting should suffice to roll forward.

**Comment by mfairman-cpi** [comment]
Based on the comments, I'll merge this and make a PR for emb-platform to bump the buildroot submodule ref (and I want to bump emb-mcu as well).

**Pull request merged**
