### PR TITLE
targets: imx distribution update to imx-5.4.47

### PR DESCRIPTION
**Pull request by vgahlan-cpi**
This patch shall update CP IMX build distribution to align with NXP imx-5.4.47 release. There is bit of more test and work pending before the merge.

There will be corresponding commits in emb-platform. Created Linus OS release branch earlier;  cp-release/imx_5.4.47_2.2.0 in emb-linux-imx

### CODE REVIEW

**Comment by chardin-cpi** [comment]
Can we do this on the 5.4.3 kernel? or this is likely a lock step merge? kernel and this at the same time - seems like that is your plan?

**Comment by vgahlan-cpi** [comment]
> Can we do this on the 5.4.3 kernel? or this is likely a lock step merge? kernel and this at the same time - seems like that is your plan?

There is intermediate step that can be done for 5.4.3. But at this point I don't see much value as that is just pre-release. Will try to wrap this week or early next week for all 3 platform.  Basically all 3 platform are up and running but there are some test and code cleanup required in emb-platform.   Also for provision update need to resolve keyctrl interface before merge.

**Comment by chardin-cpi** [comment]
> > Can we do this on the 5.4.3 kernel? or this is likely a lock step merge? kernel and this at the same time - seems like that is your plan?
> 
> There is intermediate step that can be done for 5.4.3. But at this point I don't see much value as that is just pre-release. Will try to wrap this week or early next week for all 3 platform. Basically all 3 platform are up and running but there are some test and code cleanup required in emb-platform. Also for provision update need to resolve keyctrl interface before merge.

nifty - should be fun to pop that cork

**Comment by vgahlan-cpi** [comment]
Closing this PR as there is separate PR to cover larger update.

**Pull request closed without merging**
