### PR TITLE
buildroot/upstream/package: bump up linux firmware 20201218 fw versio…

### PR DESCRIPTION
**Pull request by sudhanshugupta-cpi**
…n to 3.5

We need to update imx's SDMA fw version from 3.4 to 3.5. This is
required for proper functioning of UART4 (where RFID is connected).

UART4 is controlled by imx's SDMA driver. There seems to be some
bug in imx's sdma fw version 3.4 which restricts read on UART4_RX
(improper reading of data) and hence necessary to use proper fw
version 3.5

bump up to linux firmware to 20201218

curious minds can read this for more info
https://community.nxp.com/t5/i-MX-Processors/i-mx6ull-uart-dma-issue/td-p/1190223

PLAT-980

Signed-off-by: Vikas Gahlan <vikas.gahlan@chargepoint.com>
Signed-off-by: Sudhanshu Gupta <Sudhanshu.Gupta@chargepoint.com>

### CODE REVIEW

**Review by chardin-cpi — APPROVED** [review]

**Review by vgahlan-cpi — CHANGES_REQUESTED** [review]
This is not the correct package to update. The package to update is buildroot/package/freescale-imx/firmware-imx to 8.10 version.

**Comment by chardin-cpi** [comment]
> This is not the correct package to update. The package to update is buildroot/package/freescale-imx/firmware-imx to 8.10 version.

assumption is this was tested - is the firmware in both packages or this change was never tested?

**Comment by vgahlan-cpi** [comment]
> assumption is this was tested - is the firmware in both packages or this change was never tested?

firmware-imx contains imx6 specific firmware including SDMA. I am using latest version 8.10 and working well. In addition to firmware version, path of firmware image on target also changed.

**Comment by sudhanshugupta-cpi** [comment]
> > This is not the correct package to update. The package to update is buildroot/package/freescale-imx/firmware-imx to 8.10 version.
> 
> assumption is this was tested - is the firmware in both packages or this change was never tested?

@chardin-cpi  : your assumption is correct. The change was tested and the test output was updated on JIRA ticket (ie. RFID read working and correct SDMA FW version 3.5 loaded). See snapshot from JIRA (ignore the bad formating)...

image

@vgagliardo-cpi  : perhaps the firmware is part of both the packages. I used the packaged published by Linux Org, and you are referring to NXP's package (which I suppose would be internally using the  Linux Org's packages.

I used the highlighted tag from Linux Firmare repo.
image

Linux Firmware contains the same "imx/sdma" folder as highlighted in the snapshot below.
image

If you still feel this is the wrong package to update, I can close this PR.

**Comment by vgagliardo-cpi** [comment]
Sudhanshu,

Are you sure you have addressed your question to the right person?

I am part of the power team and have no idea what your statement means.

-Vince

**Comment by csteres-cpi** [comment]
@sudhanshugupta-cpi I think you meant to direct your comment to @vgahlan-cpi, rather than Vince?

**Comment by sudhanshugupta-cpi** [comment]
oops I am sorry .....it wasn't for you @vgagliardo-cpi 

@csteres-cpi  : thanks for correcting ...my bad.

**Comment by sudhanshugupta-cpi** [comment]
@vgahlan-cpi: As discussed in Office Hours today, I am getting these changes in for the time being, till the time your FW upgrade PR kicks in.

**Comment by chardin-cpi** [comment]
@vgahlan-cpi - it seems likely the firmware is in 2 locations, so we are bumping the linux-firmware package, since that shouldn't be an issue regardless and download the line we will be bumping the imx-firmware via the subsequent BR update as well.

**Pull request merged**
