### PR TITLE
Finbox required packages for mainline

### PR DESCRIPTION
**Pull request by trichmond-cpi**
I have added new packages to buildroot which are all public python pip projects that do not currently have an existing Buildroot package.  These packages are needed for FinBox support.  Since all of the packages are just pip's and they can be useful to others I am adding them to be upstream'd later.  One of the packages is just a version bump needed for proper udev support.

Since all of the packages are python, this should not affect any other builds.  Tested build using this branch as the submodule version in the existing FinBox build system.

- Version bump on python-pyudev.

- Added new packages to be upstreamed.

Signed-off-by: Trampus <trampus.richmond@chargepoint.com>

### CODE REVIEW

**Comment by mfairman-cpi** [comment]
Looks good at first glance, I'll give it a more thorough look.

In the meantime, one thing you could do is create a PR against emb-platform master with the buildroot submodule pointing to your commit; this will kick-off builds of all platforms so we can double-check that side of things.

**Comment by mfairman-cpi** [comment]
It looks like the panther build failed in emb-platform, something about the install step for test/panther so I will look at that...

**Comment by trichmond-cpi** [comment]
> It looks like the panther build failed in emb-platform, something about the install step for test/panther so I will look at that...

Looks like it was the QT5 test code that failed:
`2020-06-24T04:13:50.4964855Z > /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/host/bin/aarch64-none-linux-gnu-g++ -c -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os --sysroot=/actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/host/aarch64-buildroot-linux-gnu/sysroot -w -fPIC  -I. -I/actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/qt5base-5.14.2/mkspecs/devices/linux-buildroot-g++ -o main.o main.cpp
2020-06-24T04:13:50.4966592Z > main.cpp:3:4: error: #error Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129).
2020-06-24T04:13:50.4967799Z >     3 | #  error Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129).
2020-06-24T04:13:50.4968514Z >       |    ^~~~~
2020-06-24T04:13:50.4969350Z > Makefile:201: recipe for target 'main.o' failed
2020-06-24T04:13:50.4969959Z > make[3]: *** [main.o] Error 1
2020-06-24T04:13:50.4971109Z > make[3]: Leaving directory '/actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/qt5base-5.14.2/config.tests/reduce_relocations'
2020-06-24T04:13:50.4971921Z test config.qtbase.tests.reduce_relocations FAILED`

**Comment by mfairman-cpi** [comment]
Interesting... what I found was:

```
2020-06-24T04:41:34.2471751Z /usr/bin/make --no-print-directory -C test/panther install 
2020-06-24T04:41:34.2481362Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
2020-06-24T04:41:34.2481961Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
2020-06-24T04:41:34.2482512Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
2020-06-24T04:41:34.2516087Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
2020-06-24T04:41:34.2519333Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
2020-06-24T04:41:34.2525704Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
2020-06-24T04:41:34.3069623Z make[6]: *** No rule to make target '../../../host/opt/ext-toolchain/aarch64-non64-none-linux-gnu/include/c++/9.2.1/bits/stl_uninitialized.h', needed by 'lib/cppapp/src/cppapp.o'.  Stop.
2020-06-24T04:41:34.3072036Z make[5]: *** [all] Error 2
2020-06-24T04:41:34.3072515Z Makefile:35: recipe for target 'all' failed
2020-06-24T04:41:34.3074361Z make[4]: *** [install] Error 2
```
I'm not sure why this happened but I addressed the make warning about job-servers in https://github.com/ChargePoint/emb-platform/pull/130 so we'll see if that has the same issue or not.

**Comment by trichmond-cpi** [comment]
> Interesting... what I found was:
> 
> ```
> 2020-06-24T04:41:34.2471751Z /usr/bin/make --no-print-directory -C test/panther install 
> 2020-06-24T04:41:34.2481362Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> 2020-06-24T04:41:34.2481961Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> 2020-06-24T04:41:34.2482512Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> 2020-06-24T04:41:34.2516087Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
> 2020-06-24T04:41:34.2519333Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
> 2020-06-24T04:41:34.2525704Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
> 2020-06-24T04:41:34.3069623Z make[6]: *** No rule to make target '../../../host/opt/ext-toolchain/aarch64-non64-none-linux-gnu/include/c++/9.2.1/bits/stl_uninitialized.h', needed by 'lib/cppapp/src/cppapp.o'.  Stop.
> 2020-06-24T04:41:34.3072036Z make[5]: *** [all] Error 2
> 2020-06-24T04:41:34.3072515Z Makefile:35: recipe for target 'all' failed
> 2020-06-24T04:41:34.3074361Z make[4]: *** [install] Error 2
> ```
> 
> I'm not sure why this happened but I addressed the make warning about job-servers in [ChargePoint/emb-platform#130](https://github.com/ChargePoint/emb-platform/pull/130) so we'll see if that has the same issue or not.

**Comment by trichmond-cpi** [comment]
> Interesting... what I found was:
> 
> ```
> 2020-06-24T04:41:34.2471751Z /usr/bin/make --no-print-directory -C test/panther install 
> 2020-06-24T04:41:34.2481362Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> 2020-06-24T04:41:34.2481961Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> 2020-06-24T04:41:34.2482512Z make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
> 2020-06-24T04:41:34.2516087Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
> 2020-06-24T04:41:34.2519333Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
> 2020-06-24T04:41:34.2525704Z [NOTE]	Building in /actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/emb-mcu-local/.HOST-BUILD
> 2020-06-24T04:41:34.3069623Z make[6]: *** No rule to make target '../../../host/opt/ext-toolchain/aarch64-non64-none-linux-gnu/include/c++/9.2.1/bits/stl_uninitialized.h', needed by 'lib/cppapp/src/cppapp.o'.  Stop.
> 2020-06-24T04:41:34.3072036Z make[5]: *** [all] Error 2
> 2020-06-24T04:41:34.3072515Z Makefile:35: recipe for target 'all' failed
> 2020-06-24T04:41:34.3074361Z make[4]: *** [install] Error 2
> ```
> 
> I'm not sure why this happened but I addressed the make warning about job-servers in [ChargePoint/emb-platform#130](https://github.com/ChargePoint/emb-platform/pull/130) so we'll see if that has the same issue or not.


Yes I saw that too, also I see this is the QT tests are well, seems interesting that they QT tests are failing since that package was not touched.
`IC  -I. -I/actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/qt5base-5.14.2/mkspecs/devices/linux-buildroot-g++ -o main.o main.cpp
2020-06-24T04:13:51.3568530Z > main.cpp:2:10: fatal error: zstd.h: No such file or directory
2020-06-24T04:13:51.3569175Z >     2 | #include <zstd.h>
2020-06-24T04:13:51.3569737Z >       |          ^~~~~~~~
2020-06-24T04:13:51.3570154Z > compilation terminated.
2020-06-24T04:13:51.3570696Z > Makefile:181: recipe for target 'main.o' failed
2020-06-24T04:13:51.3571088Z > make[3]: *** [main.o] Error 1
2020-06-24T04:13:51.3571794Z > make[3]: Leaving directory '/actions-runner/_work/emb-platform/emb-platform/BUILD/panther/ucb/build/qt5base-5.14.2/config.tests/zstd'
2020-06-24T04:13:51.3572263Z  => source failed verification.
2020-06-24T04:13:51.3572556Z test config.qtbase.libraries.zstd FAILED`

**Pull request merged**
