### PR TITLE
swupdate: update version from 2021.11 to 2022.12

### PR DESCRIPTION
**Pull request by carlnorum-cpi**
swupdate has upstream patches that fix some of our hangs during OTA. Grab the newest version to get those fixes.

Fixes: [PLAT-7072]

[PLAT-7072]: https://chargepoint.atlassian.net/browse/PLAT-7072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jhart-cpi — APPROVED** [review]

**Comment by carlnorum-cpi** [comment]
I tested so far as copying a `.swu` file over and running this command roger gave me:

    swupdate -v -k /opt/local/etc/emb-certs/swupdate/swu-root-dev.crt  -i /tmp/secureboot-chargepoint-ucb.swu

It succeeded. I sent him my local build dfu zip file and the swu file for more aggressive testing.

**Comment by carlnorum-cpi** [comment]
I did some commit digging in the swupdate repo, and the version we're already using, `2021.11`, already has the patch described here: https://groups.google.com/g/swupdate/c/r0DqIVJsUsg/m/TcIQtZvbDAAJ?pli=1 which we thought was a potential culprit.

**Comment by chardin-cpi** [comment]
There are more commits upstream - the install staging and extra config look interesting as well ... if you want to cherry-pick -x to get something like this

```
commit e662af931cb16535073f0fa80c9367ce4ea3bab0
Author: Ricardo Martincoski <ricardo.martincoski@gmail.com>
Date:   Sun Jan 1 20:36:47 2023 -0300

    package/swupdate: drop dangling SWUPDATE_BUILD_CONFIG
    
    "6c63e4de4a boot/swupdate: don't specify .config to munge" dropped all
    usages of this define but the define itself was left dangling.
    
    Drop it now.
    
    Signed-off-by: Ricardo Martincoski <ricardo.martincoski@gmail.com>
    Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
    (cherry picked from commit ca5cd8d67554c568daee4da1f058bcf3b35b2976)

commit 8ec50093bbc973aacff86373e783d8c8efcb3233
Author: James Hilliard <james.hilliard1@gmail.com>
Date:   Tue Dec 13 14:10:49 2022 -0700

    package/swupdate: bump to version 2022.12
    
    Drop patch which is now upstream.
    
    Update service files based on latest versions in:
    https://github.com/sbabic/meta-swupdate/tree/master/recipes-support/swupdate/swupdate
    
    Signed-off-by: James Hilliard <james.hilliard1@gmail.com>
    Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
    (cherry picked from commit 8ef654997caba04dffecdc4105b214abf7d02ae5)

commit d12bae0fd920616a79c6a2ee53a172530fb81c5a
Author: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Date:   Sun Dec 11 14:42:01 2022 +0100

    package/swupdate: indent with tabs
    
    Commit eb2f2886b2364e5b6a0867f55106bf83acb064e7 ("package/swupdate:
    add staging install") has introduced some commands indented with
    spaces, which check-package doesn't like.
    
    Fix that by using tabs instead, and while we're at it, wrap the line
    that is a bit too long.
    
    Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
    (cherry picked from commit 65e0351adc5075ac679557d7e41a02815f979e90)

commit 62cd8391f91063cf7aa766cfd36f6b7e880eca9f
Author: Andrey Grafin <conquistador@yandex-team.ru>
Date:   Fri Dec 9 00:03:28 2022 +0300

    package/swupdate: add staging install
    
    SWupdate provides API for external programs, so some headers and
    libraries must be install to staging.
    
    This patch installs headers and libs to STAGING_DIR, to prevent a
    header name collision a subdirectory /usr/include/swupdate creates.
    
    Signed-off-by: Andrey Grafin <conquistador@yandex-team.ru>
    Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
    (cherry picked from commit eb2f2886b2364e5b6a0867f55106bf83acb064e7)
```

**Comment by amadhusudan-cpi** [comment]
This PR is raised against a closed ticket, on a release which is done. 
Please spin off a new ticket and do this there on r2023.03.00 or a later branch please

If this gets merged as part of this ticket, it will confuse everyone and B&R as well

CC: @chardin-cpi @carlnorum-cpi @jhart-cpi

**Pull request closed without merging**
